import {theme} from './fan-data.js';
let state={notices:[],sources:[]},selection={artists:[],selectedArtist:''},limit=12;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function relatedNotices(e){return state.notices.filter(n=>n.artist===e.artist&&n.countries.includes(e.country)).slice(0,4);}
export function renderAnnouncements(next){if(next)selection=next;const type=$('#announcement-type').value,country=$('#announcement-country').value;const list=state.notices.filter(n=>(selection.artists.includes(n.artist)||n.festival?.artists.some(a=>selection.artists.includes(a)))&&(!selection.selectedArtist||n.artist===selection.selectedArtist||n.festival?.artists.includes(selection.selectedArtist))&&(type==='all'||n.kind===type||(type==='ticket'&&n.snippets.length>0))&&(country==='all'||n.kind==='comeback'||n.countries.includes(country)));$('#announcement-count').textContent=list.length;
 $('#announcement-list').innerHTML=list.slice(0,limit).map(n=>{const g=theme(n.artist);return `<article class="notice-card" style="--ink:${g[2]};--tint:${g[3]}"><span class="notice-tag">${esc(n.artist)} · ${n.kind==='festival'?'拼盤／音樂節':n.kind==='comeback'?'回歸／發行':n.kind==='ticket'?'售票／預售':'演唱會／巡演'} · ${n.kind==='comeback'?'發行日':n.countries.join(' / ')}</span><div class="notice-title"><h3><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">${esc(n.title)} ↗</a></h3>${(n.uncertaintyReasons||[]).length?`<details class="uncertainty"><summary aria-label="查看待確認資訊" title="有資訊需要確認">?</summary><div><b>需要確認</b><ul>${n.uncertaintyReasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">查看原公告 ↗</a></div></details>`:''}</div>${n.kind==='comeback'?`<p class="release-date">發行日：${esc(n.release?.date||'待確認（暫不加入月曆）')}</p>`:''}${n.snippets.length?`<details><summary>售票時間原文</summary><p>${esc(n.snippets.join('\n'))}</p></details>`:''}<small>首次收錄 ${new Date(n.firstDetectedAt).toLocaleDateString('zh-TW')}</small></article>`;}).join('')||'<p class="empty">尚未收錄符合條件的公開公告。</p>';$('#more-announcements').hidden=list.length<=limit;
 $('#announcement-status').textContent=state.syncing?'正在核對八個團體的公開公告…':state.updatedAt?`最近檢查 ${new Date(state.updatedAt).toLocaleString('zh-TW')} · 每 30 分鐘更新`:'尚未完成公告更新';$('#announcement-sources').textContent=state.sources.map(s=>`${s.artist}：${s.ok?'已讀取':s.error}`).join('；');}
async function load(sync=false){try{const r=await fetch(sync?'/api/announcements/sync':'/api/announcements',{method:sync?'POST':'GET'});if(!r.ok)throw Error();state=await r.json();renderAnnouncements();if(!state.syncing)window.dispatchEvent(new Event('encore-notices-updated'));if(state.syncing)setTimeout(()=>load(),4000);}catch{$('#announcement-status').textContent='公告服務暫時無法連線，請稍後重試。';}}
export function initAnnouncements(){$('#refresh-announcements').onclick=()=>load(true);$('#announcement-type').onchange=$('#announcement-country').onchange=()=>{limit=12;renderAnnouncements();};$('#more-announcements').onclick=()=>{limit+=12;renderAnnouncements();};load();setInterval(()=>load(),60000);}

