import {initEmailNotifications} from './email-ui.js';
import {initAuth} from './auth.js';
import {raffleStatus,raffleTime} from './raffle-ui.js';
import {avatars} from './avatar-data.js';
import {theme,recurring,daysUntil,ticketSites} from './fan-data.js';
import {initAnnouncements,renderAnnouncements,relatedNotices} from '/announcements.js';
const $=s=>document.querySelector(s);
const DEFAULT=['TXT','RIIZE','&TEAM','BOYNEXTDOOR','CORTIS','ENHYPEN','NCT WISH','BTS'];
const countryNames={TW:'台灣',JP:'日本',KR:'韓國'};
const slugs={TXT:'txt',RIIZE:'riize','&TEAM':'andteam',BOYNEXTDOOR:'boynextdoor',CORTIS:'cortis',ENHYPEN:'enhypen','NCT WISH':'nctwish',BTS:'bts'};
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
let artists=stored('encore.artists',DEFAULT);if(!Array.isArray(artists)||artists.some(a=>typeof a!=='string'))artists=[...DEFAULT];
let saved=stored('encore.saved',[]);if(!Array.isArray(saved))saved=[];
let attending=stored('encore.attending',{});if(!attending||typeof attending!=='object'||Array.isArray(attending))attending={};
const allEvents=()=>[...data.events,...recurring(month.getFullYear()).filter(followed)].sort((a,b)=>a.date.localeCompare(b.date));
const tint=e=>{const g=theme(e.artist+' '+e.title);return `--ink:${g[2]};--tint:${g[3]}`;};
const kind=e=>e.kind==='raffle'?'🎟':e.eventType==='festival'?'🎤':e.kind==='comeback'?'💿':e.kind==='birthday'?'🎂':e.kind==='anniversary'?'✦':'♫';
let data={events:[],sources:[]},month=new Date(),selectedDay=null,selectedArtist='',mode='calendar',isLoading=true;
month=new Date(month.getFullYear(),month.getMonth(),1);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const safeLink=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentUser=null,authGeneration=0;
const personalKey=key=>currentUser?key+':'+currentUser.id:key;
function persist(key,value){try{localStorage.setItem(personalKey(key),JSON.stringify(value));return true;}catch{$('#status').textContent='瀏覽器無法儲存偏好，本次設定仍可使用。';return false;}}
const normalize=s=>String(s||'').toLocaleLowerCase().replace(/[\s\-_:]/g,'');
function matches(e,artist){if(e.artists?.includes(artist))return true;const aliases=artist.toUpperCase()==='TXT'?['TXT','TOMORROW X TOGETHER','투모로우바이투게더']:artist.toUpperCase()==='BTS'?['BTS','防彈少年團','방탄소년단']:[artist];return aliases.some(a=>normalize(`${e.artist} ${e.title}`).includes(normalize(a)));}
const followed=e=>artists.some(a=>matches(e,a));
function filtered(){const query=normalize($('#search').value);const scope=$('#scope').value;const country=$('#country')?.value||'all';return allEvents().filter(e=>(!query||normalize(e.title+' '+e.artist+' '+e.venue).includes(query))&&(!selectedArtist||matches(e,selectedArtist))&&(country==='all'||['birthday','anniversary','comeback'].includes(e.kind)||e.country===country)&&($('#event-kind').value==='all'||(e.kind||'concert')===$('#event-kind').value||($('#event-kind').value==='festival'&&e.eventType==='festival'))&&followed(e)&&(scope!=='saved'||saved.includes(e.id)));}
function monthEvents(){const prefix=dateKey(month).slice(0,7);return filtered().filter(e=>e.date.startsWith(prefix));}
function setMonth(year,m){month=new Date(year,m,1);selectedDay=null;render();}
function renderArtists(){const colors=['#e9f1ff','#ffeadc','#e4f3e9','#fce6ed','#eef1d9','#eee8fc','#dff4f3','#e9edfa'];$('#artists').innerHTML=artists.map((a,i)=>`<button class="artist-button ${selectedArtist===a?'active':''}" data-artist="${escape(a)}" style="--tint:${theme(a)[3]};--ink:${theme(a)[2]}" aria-pressed="${selectedArtist===a}"><span class="avatar" style="--tint:${theme(a)[3]};--ink:${theme(a)[2]}">${avatars[a]?`<img src="${escape(avatars[a])}" alt="${escape(a)} Weverse 頭像" referrerpolicy="no-referrer">`:'✦'}</span>${escape(a)}</button>`).join('');$('#artists').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedArtist=selectedArtist===b.dataset.artist?'':b.dataset.artist;selectedDay=null;render();});}
function lineup(e){return e.eventType==='festival'?`<div class="festival-artists"><span>拼盤／音樂節 · 已收錄出演團體</span>${(e.lineupLabels||e.artists||[]).map(a=>`<span class="lineup-tag" style="--ink:${theme(a)[2]};--tint:${theme(a)[3]}">${escape(a)}</span>`).join('')}</div>`:'';}
function card(e){return `<button class="event-card" style="${tint(e)}" data-event="${escape(e.id)}"><span class="event-date">${escape(e.date.replaceAll('-','.'))} · ${escape(e.kind&&e.kind!=='raffle'?'全天':e.time||'時間待確認')}${saved.includes(e.id)?' ★':''}</span><h3>${kind(e)} ${escape(e.title)}${e.uncertaintyReasons?.length?' <span class="uncertain-mark" aria-label="有待確認資訊">?</span>':''}</h3><p>${escape(e.venue)}</p>${lineup(e)}<span class="tag">${countryNames[e.country]||(e.kind==='raffle'?'GLOBAL 日本巡演抽選':e.kind==='comeback'?'回歸／發行':e.kind?'每年紀念日':'地區待確認')}</span> <span class="tag">${followed(e)?'我的團體':escape(e.source)}</span></button>`;}
function bindCards(container){container.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>showEvent(b.dataset.event));}
function render(){
  renderRaffles();renderCountdowns();renderArtists();renderAnnouncements({artists,selectedArtist});const events=monthEvents();const today=dateKey(new Date());
  $('#month-title').textContent=`${month.getFullYear()}年 ${month.getMonth()+1}月`;
  $('#month-count').textContent=isLoading?'—':events.length;
  $('#follow-count').textContent=isLoading?'—':events.filter(followed).length;
  const next=filtered().find(e=>!e.kind&&e.date>=today&&followed(e));$('#next-event').textContent=next?`${next.date.slice(5).replace('-','/')}  ${next.artist||artists.find(a=>matches(next,a))} · ${countryNames[next.country]}`:isLoading?'正在尋找':'尚未收錄符合條件的場次';
  $('#calendar').hidden=mode!=='calendar';$('#event-list').hidden=mode!=='list';$('#calendar-view').setAttribute('aria-pressed',mode==='calendar');$('#list-view').setAttribute('aria-pressed',mode==='list');
  const start=new Date(month);start.setDate(1-month.getDay());const cells=[];const days=Math.ceil((month.getDay()+new Date(month.getFullYear(),month.getMonth()+1,0).getDate())/7)*7;
  for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d);const dayEvents=events.filter(e=>e.date===key);cells.push(`<div class="day ${d.getMonth()!==month.getMonth()?'outside':''} ${today===key?'today':''} ${selectedDay===key?'selected':''}" aria-label="${key}，${dayEvents.length} 個活動" ><button class="date" data-day="${key}" aria-label="${key}">${d.getDate()}</button>${dayEvents.slice(0,2).map(e=>`<button class="event-chip" data-event="${escape(e.id)}" style="${tint(e)}" title="${escape(e.title)}">${kind(e)} ${saved.includes(e.id)?'★ ':''}${escape(e.kind||e.eventType==='festival'?e.title:e.artist||e.title)}${e.uncertaintyReasons?.length?' ?':''}</button>`).join('')}${dayEvents.length>2?`<span class="more">+${dayEvents.length-2} 個活動</span>`:''}</div>`);}
  $('#calendar').innerHTML=`<div class="weekdays">${['日','一','二','三','四','五','六'].map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div>`;
  bindCards($('#calendar'));$('#calendar').querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;render();});
  const empty=`<div class="empty"><b>${isLoading?'正在讀取場次…':'尚未收錄符合條件的演出'}</b>${isLoading?'首次更新需要一點時間。':'試試其他月份或篩選條件。<br>尚未收錄不代表沒有演出。'}</div>`;
  $('#event-list').innerHTML=events.length?events.map(card).join(''):empty;bindCards($('#event-list'));
  $('#agenda-title').textContent=selectedDay?`${selectedDay.slice(5).replace('-','月')}日 的演出`:'接下來的演出';$('#clear-day').hidden=!selectedDay;
  const agenda=selectedDay?filtered().filter(e=>e.date===selectedDay):filtered().filter(e=>e.date>=today).slice(0,6);
  $('#agenda-hint').textContent=selectedDay?'點選活動查看詳情':'依目前篩選 · 最近 6 場';$('#agenda-events').innerHTML=agenda.length?agenda.map(card).join(''):empty;bindCards($('#agenda-events'));
}
function showEvent(id){const e=allEvents().find(e=>e.id===id)||attending[id];if(!e)return;$('#detail-body').innerHTML=`<p class="eyebrow">${escape(e.artist||'LIVE CONCERT')} · ${countryNames[e.country]||(e.kind==='raffle'?'GLOBAL 日本巡演抽選':e.kind==='comeback'?'回歸／發行':'生日與紀念日')}</p><h2>${escape(e.title)}</h2>${e.raffle?`<div class="raffle-detail"><b>${escape(e.raffle.label)} · ${raffleStatus(e.raffle)}</b><p>${raffleTime(e.raffle.start)} ～ ${raffleTime(e.raffle.end)}（日本時間）<br>台灣：${raffleTime(e.raffle.start,'Asia/Taipei')} ～ ${raffleTime(e.raffle.end,'Asia/Taipei')}</p>${e.raffle.requiresRegistration?'<strong>需已完成 Weverse 事前登記。</strong>':''}</div>`:''}${lineup(e)}${e.uncertaintyReasons?.length?`<div class="uncertainty-message"><b>？需要確認</b><ul>${e.uncertaintyReasons.map(r=>`<li>${escape(r)}</li>`).join('')}</ul></div>`:''}<div class="detail-meta">日期　${escape(e.date)}<br>時間　${escape(e.kind&&e.kind!=='raffle'?'全天':e.time||'來源未提供，請確認官方公告')}<br>時區　${escape(e.kind&&e.kind!=='raffle'?'全天日期，不換算時區':e.timezone)}<br>地點　${escape(e.venue)}${e.address?'<br>地址　'+escape(e.address):''}${e.price?'<br>票價　'+escape(e.price):''}${e.saleAt?'<br>售票開始　'+escape(e.saleAt):''}</div>${e.noticeTitle?`<p class="muted">原公告標題：${escape(e.noticeTitle)}</p>`:''}<p class="description">${escape(e.description||'完整活動與售票資訊請見原始公告。')}</p><p class="muted">資料來源：${escape(e.source)}<br>來源可能調整或取消場次，出發與購票前請再次核對。</p><div class="attendance">${!e.kind?`<label><input id="attend" type="checkbox" ${attending[e.id]?'checked':''}> 我會到場 · 加入倒數</label>`:''}</div><div class="detail-actions"><button id="toggle-save" class="primary">${saved.includes(e.id)?'★ 取消收藏':'☆ 收藏演出'}</button><a href="${escape(safeLink(e.sourceUrl))}" target="_blank" rel="noopener noreferrer">官方來源 ↗</a>${e.ticketUrl?`<a href="${escape(safeLink(e.ticketUrl))}" target="_blank" rel="noopener noreferrer">售票資訊 ↗</a>`:''}<button id="export-event">匯出行事曆</button></div>`;
  if($('#attend'))$('#attend').onchange=()=>{if($('#attend').checked)attending[e.id]=e;else delete attending[e.id];persist('encore.attending',attending);renderCountdowns();};
  $('#detail-body').insertAdjacentHTML('beforeend',e.kind?'':`<details class="sources-detail"><summary>相關團體公告與售票平台</summary><p>以下公告依團體與地區比對，請核對場次；平台連結供自行搜尋，不代表該場正在售票。</p>${relatedNotices(e).map(n=>`<p><a href="${escape(n.url)}" target="_blank" rel="noopener noreferrer">${escape(n.title)} ↗</a></p>`).join('')}<div class="notice-links">${ticketSites.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')}</div></details>`);
  $('#toggle-save').onclick=()=>{saved=saved.includes(e.id)?saved.filter(x=>x!==e.id):[...saved,e.id];persist('encore.saved',saved);render();showEvent(id);};$('#export-event').onclick=()=>exportEvent(e);if(!$('#detail').open)$('#detail').showModal();
}
function exportEvent(e){const esc=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const date=e.date.replaceAll('-','');const dt=e.time?`DTSTART;TZID=${e.timezone}:${date}T${e.time.replace(':','')}00`:`DTSTART;VALUE=DATE:${date}`;const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Encore//Calendar//ZH','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${e.id}@encore.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,dt,`SUMMARY:${esc(e.title)}`,`LOCATION:${esc(e.venue)}`,`DESCRIPTION:${esc(e.source+'\n'+e.sourceUrl+'\n'+(e.time?'':'開演時間未提供，請查閱來源。'))}`,`URL:${e.sourceUrl}`,'END:VEVENT','END:VCALENDAR'];const blob=new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='encore-'+e.date+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderStatus(){const failed=data.sources.filter(s=>!s.ok);const good=data.sources.filter(s=>s.ok).length;$('#status').classList.toggle('error',failed.length>0);$('#status').textContent=isLoading?'首次更新中，正在讀取官方場次…':`${data.updatedAt?'最近檢查 '+new Date(data.updatedAt).toLocaleString('zh-TW'):'尚未完成更新'} · ${good}/${data.sources.length} 個來源正常 · 網站啟動時每 6 小時更新${failed.length?' · 部分來源失敗，保留上次資料':''}`;
  $('#source-status').innerHTML=data.sources.map(s=>`<li><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.name)} ↗</a><span>${s.ok?'已讀取 '+s.count+' 場':escape(s.error||'尚未連線')}${s.updatedAt?' · '+new Date(s.updatedAt).toLocaleString('zh-TW'):''}</span></li>`).join('');}
async function load(sync=false){$('#sync').disabled=true;try{const response=await fetch(sync?'/api/sync':'/api/events',{method:sync?'POST':'GET'});if(!response.ok)throw new Error('連線失敗');data=await response.json();isLoading=data.syncing&&!data.updatedAt;render();renderStatus();if(data.syncing)setTimeout(()=>load(),2000);}catch{$('#status').textContent='無法連線到網站服務。請確認啟動視窗仍在執行，再按更新重試。';$('#status').classList.add('error');isLoading=false;render();}finally{$('#sync').disabled=false;}}
$('#prev').onclick=()=>setMonth(month.getFullYear(),month.getMonth()-1);$('#next').onclick=()=>setMonth(month.getFullYear(),month.getMonth()+1);$('#today').onclick=()=>{const d=new Date();setMonth(d.getFullYear(),d.getMonth());};$('#sync').onclick=()=>{$('#status').textContent='正在重新讀取官方來源…';load(true);};$('#calendar-view').onclick=()=>{mode='calendar';render();};$('#list-view').onclick=()=>{mode='list';render();};$('#search').oninput=()=>{selectedDay=null;render();};$('#scope').onchange=()=>{selectedDay=null;render();};$('#clear-day').onclick=()=>{selectedDay=null;render();};

function openArtists(){
 $('#artist-options').innerHTML=DEFAULT.map(a=>`<label class="follow-option" style="--ink:${theme(a)[2]};--tint:${theme(a)[3]}"><input type="checkbox" value="${escape(a)}" ${artists.includes(a)?'checked':''}><span class="avatar"><img src="${escape(avatars[a])}" alt="" referrerpolicy="no-referrer"></span>${escape(a)}</label>`).join('');
 if(!$('#artist-dialog').open)$('#artist-dialog').showModal();
}
async function preferences(method='GET',followedArtists){const r=await fetch('/api/auth/follows',{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:method==='PUT'?JSON.stringify({followedArtists}):undefined});const d=await r.json();if(!r.ok){const e=Error(d.error||'無法儲存追蹤設定');e.status=r.status;throw e;}return d;}
$('#edit-artists').onclick=()=>{if(!currentUser){$('#open-login').click();return;}$('#artist-message').textContent='';openArtists();};
$('#save-artists').onclick=async()=>{if(!currentUser)return;const generation=authGeneration;const chosen=[...$('#artist-options').querySelectorAll('input:checked')].map(x=>x.value);$('#save-artists').disabled=true;$('#artist-message').textContent='儲存中…';try{const d=await preferences('PUT',chosen);if(generation!==authGeneration)return;artists=d.followedArtists.filter(a=>DEFAULT.includes(a));persist('encore.follow-draft',null);persist('encore.artists',artists);selectedArtist='';$('#artist-dialog').close();render();$('#follow-status').textContent=artists.length?'已同步你的追蹤團體':'尚未追蹤團體，點選「編輯」開始選擇。';}catch(e){if(generation===authGeneration){if(e.status===401||e.status===403){$('#artist-message').textContent=e.message;}else{artists=chosen;selectedArtist='';const stored=persist('encore.follow-draft',chosen);render();$('#artist-message').textContent=stored?'已儲存於此瀏覽器，月曆已更新；尚未同步雲端。完成 SQL 設定後，再按儲存即可同步。':'月曆已更新，但瀏覽器與雲端都未能儲存，請勿關閉此頁。';$('#follow-status').textContent=$('#artist-message').textContent;}}}finally{$('#save-artists').disabled=false;}};
window.addEventListener('encore-auth-change',async({detail})=>{
 const generation=++authGeneration;currentUser=detail.user;selectedArtist='';selectedDay=null;$('#artist-dialog').close();$('#detail').close();
 saved=stored(personalKey('encore.saved'),[]);if(!Array.isArray(saved))saved=[];
 attending=stored(personalKey('encore.attending'),{});if(!attending||typeof attending!=='object'||Array.isArray(attending))attending={};
 const draft=currentUser?stored(personalKey('encore.follow-draft'),null):null;const validDraft=Array.isArray(draft)&&draft.every(a=>DEFAULT.includes(a));artists=currentUser?(validDraft?draft:[]):DEFAULT;render();$('#follow-status').textContent=currentUser?'正在讀取你的追蹤團體…':'登入後可選擇追蹤團體。';
 if(!currentUser)return;
 try{const d=await preferences();if(generation!==authGeneration)return;if(validDraft){$('#follow-status').textContent='有尚未同步的追蹤設定；請按儲存同步至雲端。';$('#artist-message').textContent=$('#follow-status').textContent;openArtists();return;}artists=d.followedArtists.filter(a=>DEFAULT.includes(a));persist('encore.artists',artists);render();$('#follow-status').textContent=artists.length?'已同步你的追蹤團體':'選擇你想追蹤的團體，建立專屬行事曆。';if(!d.exists){$('#artist-message').textContent='勾選團體後儲存。';openArtists();}}
 catch(e){if(generation===authGeneration){if(!validDraft){const cached=stored(personalKey('encore.artists'),[]);artists=Array.isArray(cached)?cached.filter(a=>DEFAULT.includes(a)):[];}render();$('#follow-status').textContent='雲端追蹤設定尚未連線，可先在此瀏覽器選團使用。';$('#artist-message').textContent=e.message+' 你仍可勾選並儲存於此瀏覽器。';openArtists();}}
});
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
// Local controls share one state path with optional agent tools.
const country=document.createElement('select');country.id='country';country.setAttribute('aria-label','地區');country.innerHTML='<option value="all">台・日・韓</option><option value="TW">台灣</option><option value="JP">日本</option><option value="KR">韓國</option>';$('.filters').append(country);country.onchange=()=>{selectedDay=null;render();};
const typeFilter=document.createElement('select');typeFilter.id='event-kind';typeFilter.setAttribute('aria-label','活動類型');typeFilter.innerHTML='<option value="all">所有活動</option><option value="concert">演唱會（含拼盤）</option><option value="festival">拼盤／音樂節</option><option value="raffle">GLOBAL 抽選登記</option><option value="comeback">回歸／發行</option><option value="birthday">成員生日</option><option value="anniversary">出道紀念日</option>';$('.filters').append(typeFilter);typeFilter.onchange=()=>render();
const rafflePanel=document.createElement('section');rafflePanel.id='raffle-deadlines';$('.agenda').after(rafflePanel);
function renderRaffles(){const windows=[...new Map(data.events.filter(e=>e.kind==='raffle'&&followed(e)&&(!selectedArtist||matches(e,selectedArtist))).map(e=>[e.raffle.id,e])).values()].filter(e=>Date.parse(e.raffle.end)>=Date.now()).sort((a,b)=>Date.parse(a.raffle.end)-Date.parse(b.raffle.end));rafflePanel.hidden=!windows.length;rafflePanel.innerHTML='<h2>GLOBAL 日本巡演 · 登記與抽選</h2>'+windows.map(e=>`<button class="raffle-card" style="${tint(e)}" data-event="${escape(e.id)}"><b>${escape(e.artist)} · ${escape(e.raffle.label)}</b><span class="raffle-status">${raffleStatus(e.raffle)}</span><span>${raffleTime(e.raffle.start)} ～ ${raffleTime(e.raffle.end)}（日本時間）</span><small>台灣：${raffleTime(e.raffle.start,'Asia/Taipei')} ～ ${raffleTime(e.raffle.end,'Asia/Taipei')}</small>${e.raffle.requiresRegistration?'<strong class="raffle-prerequisite">須先完成 Weverse 事前登記；錯過者不能直接參加此階段。</strong>':''}</button>`).join('');bindCards(rafflePanel);}
setInterval(()=>{renderRaffles();},60000);
const countdown=document.createElement('section');countdown.id='countdowns';countdown.setAttribute('aria-label','我的到場倒數');$('.calendar-panel').before(countdown);
function renderCountdowns(){const events=Object.values(attending).map(e=>data.events.find(x=>x.id===e.id)||e).filter(e=>followed(e)&&!e.kind&&daysUntil(e.date,e.timezone)>=0).sort((a,b)=>a.date.localeCompare(b.date));countdown.hidden=!events.length;countdown.innerHTML=events.map(e=>`<button class="countdown" style="${tint(e)}" data-event="${escape(e.id)}"><strong>${daysUntil(e.date,e.timezone)===0?'D-DAY':'D-'+daysUntil(e.date,e.timezone)}</strong><span>${escape(e.title)}</span></button>`).join('');bindCards(countdown);}
setInterval(renderCountdowns,60000);
const ticketDirectory=document.createElement('details');ticketDirectory.className='sources-detail';ticketDirectory.innerHTML='<summary>售票網站快捷連結</summary><p>平台供自行查詢；不代表全部已自動串接或有票。</p><div class="notice-links">'+ticketSites.map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${n} ↗</a>`).join('')+'</div>';$('.announcements').append(ticketDirectory);
const sources=document.createElement('details');sources.className='sources-detail';sources.innerHTML='<summary>資料涵蓋範圍與連線狀態</summary><p>台灣：文化部公開收錄場次。日本：已串接團體官方行程首頁。韓國：來源有明確標示的演出與 Weverse 公告。未包含所有團體與場次，也不自動同步 Weverse 追蹤變更。</p><ul id="source-status"></ul><p>RIIZE、NCT WISH 公告由公開 Weverse 頁面偵測；只有可明確解析的演出日期才加入月曆。新增追蹤名稱只會篩選現有來源，不會自動新增資料來源。</p><div class="notice-links"></div>';$('footer').before(sources);$('.notice-links').innerHTML=DEFAULT.map(a=>`<a href="https://weverse.io/${slugs[a]}/notice" target="_blank" rel="noopener noreferrer">${escape(a)} 公告 ↗</a>`).join('');$('#coverage').textContent='台灣公開資料 + 藝人官方行程';
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'show_concert_month',description:'切換演唱會行事曆的月份和地區，回傳目前收錄的場次。',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:2000,maximum:2100},month:{type:'integer',minimum:1,maximum:12},country:{type:'string',enum:['all','TW','JP','KR']}},required:['year','month'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!Number.isInteger(input.year)||input.year<2000||input.year>2100||!Number.isInteger(input.month)||input.month<1||input.month>12||input.country&&!['all','TW','JP','KR'].includes(input.country))throw new Error('月份或地區無效');if(input.country)country.value=input.country;setMonth(input.year,input.month-1);return {events:monthEvents().map(({title,date,country,sourceUrl})=>({title,date,country,sourceUrl}))};}})).catch(()=>{});}catch{}}
window.addEventListener('encore-notices-updated',()=>load());initAuth();initEmailNotifications(()=>artists);initAnnouncements();render();load();setInterval(()=>load(),5*60*1000);




